// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"advanced-scenarios.md": () => import("../content/docs/advanced-scenarios.md?collection=docs"), "community-license.md": () => import("../content/docs/community-license.md?collection=docs"), "constraints.md": () => import("../content/docs/constraints.md?collection=docs"), "daily-workflows.md": () => import("../content/docs/daily-workflows.md?collection=docs"), "faqs.md": () => import("../content/docs/faqs.md?collection=docs"), "filesystem-content-handling.md": () => import("../content/docs/filesystem-content-handling.md?collection=docs"), "getting-started.md": () => import("../content/docs/getting-started.md?collection=docs"), "ignoring-files.md": () => import("../content/docs/ignoring-files.md?collection=docs"), "index.md": () => import("../content/docs/index.md?collection=docs"), "project-configuration.md": () => import("../content/docs/project-configuration.md?collection=docs"), "real-world-workflows.md": () => import("../content/docs/real-world-workflows.md?collection=docs"), "structure-language.md": () => import("../content/docs/structure-language.md?collection=docs"), "commands/command-reference.md": () => import("../content/docs/commands/command-reference.md?collection=docs"), "commands/flags-reference.md": () => import("../content/docs/commands/flags-reference.md?collection=docs"), "commands/index.md": () => import("../content/docs/commands/index.md?collection=docs"), "commands/positional-arguments.md": () => import("../content/docs/commands/positional-arguments.md?collection=docs"), "release/v3.md": () => import("../content/docs/release/v3.md?collection=docs"), "commands/commands/create.md": () => import("../content/docs/commands/commands/create.md?collection=docs"), "commands/commands/delete.md": () => import("../content/docs/commands/commands/delete.md?collection=docs"), "commands/commands/find.md": () => import("../content/docs/commands/commands/find.md?collection=docs"), "commands/commands/generate.md": () => import("../content/docs/commands/commands/generate.md?collection=docs"), "commands/commands/init.md": () => import("../content/docs/commands/commands/init.md?collection=docs"), "commands/commands/list.md": () => import("../content/docs/commands/commands/list.md?collection=docs"), "commands/commands/merge.md": () => import("../content/docs/commands/commands/merge.md?collection=docs"), "commands/commands/rename.md": () => import("../content/docs/commands/commands/rename.md?collection=docs"), "commands/commands/update.md": () => import("../content/docs/commands/commands/update.md?collection=docs"), "commands/commands/validate.md": () => import("../content/docs/commands/commands/validate.md?collection=docs"), }),
};
export default browserCollections;